name: diffusion
description: Native Dart Diffusion library for Dart. Use diffusion pipelines like Stable Diffusion, Flux, Qwen2D, etc to generate images, videos and audio.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  tensor:
  kamma:
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

dependency_overrides:
  tensor:
    path: ../tensor
  kamma:
    path: ../kamma